### ISSUE TITLE
Installation of the Agent on multiple instances

### ISSUE THREAD

**Issue by 00alis** [arduino/arduino-create-agent#185] opened 2017-10-10 08:15 UTC
all the infos in this thread
https://forum.arduino.cc/index.php?topic=415177.0

**Comment by 00alis** [comment] 2017-10-10 08:20
https://github.com/arduino/arduino-create-agent/releases/tag/1.1.60

**Comment by zmoog** [comment] 2021-02-02 10:57
Duplicate of #118.

**Closed by zmoog** 2021-02-02 10:57 UTC
