### ISSUE TITLE
debug console does not work on firefox

### ISSUE THREAD

**Issue by mastrolinux** [arduino/arduino-create-agent#161] opened 2017-07-07 15:49 UTC
I just tested FF version 54.0 and the agent does not display any info in the debug console at https://localhost:8992

The form is present but there is no output.

**Comment by mastrolinux** [comment] 2017-07-07 15:57
```TypeError: msg.indexOf is not a function[Learn More]  localhost:8992:19:50
	appendLog https://localhost:8992/:19:50
	<anonymous> https://localhost:8992/:53:13
	[9]</n.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:13388
	[5]</r.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:8384
	[5]</r.prototype.onclose https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:8961
	[8]</e.exports/< https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:12320
	[9]</n.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:13388
	[3]</n.prototype.onclose https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:6040
	[8]</e.exports/< https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:12320
	[9]</n.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:13388
	[13]</</r.prototype.onClose https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:23258
	[13]</</r.prototype.setTransport/< https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:18049
	[9]</n.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:13388
	[14]</n.prototype.onClose https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:1:24974
	[19]</n.prototype.onClose https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js:2:3612
	[19]</n.prototype.addEventListeners/this.ws.onclose```

**Comment by BallscrewBob** [comment] 2017-08-17 03:13
Should that not be 8991 ?

**Comment by hannobraun** [comment] 2018-01-29 07:39
The debug console works for me in Firefox 58.0 on Window 10 and Linux.

@mastrolinux Can you still reproduce?

**Comment by zmoog** [comment] 2021-02-02 10:21
Works on Linux in Firefox 84.0.2. 

Closing this issue, feel free to comment or reopen.

**Closed by zmoog** 2021-02-02 10:21 UTC
Labels: priority:high, type:bug
