### ISSUE TITLE
Installation issue: "destination ${windows_folder_startup} resolved to an empty value"

### ISSUE THREAD

**Issue by smellai** [arduino/arduino-create-agent#118] opened 2016-08-17 07:23 UTC
http://forum.arduino.cc/index.php?topic=415177.0
http://forum.arduino.cc/index.php?topic=418883.new#new

**Comment by smellai** [comment] 2016-09-22 07:29
Another one with windows 7
http://forum.arduino.cc/index.php?topic=425344.new#new

**Comment by facchinm** [comment] 2017-02-21 13:55
see also https://github.com/arduino/Arduino/issues/6010

**Comment by facchinm** [comment] 2017-02-21 13:56
@anyoneInterested if you could test the development installer and report the result here it would be great. Direct link: http://downloads.arduino.cc/CreateBridge/staging/ArduinoCreateAgent-1.0-windows-installer.exe

**Comment by fonix232** [comment] 2017-04-19 10:27
I'm having the same issue on Windows 10 Pro (1607). Corporate environment, with main user not having admin rights and using a pseudo-user as SA to install stuff.

This issue happens on both the linked 1.0 development installer, and the 1.1 official.

**Comment by smellai** [comment] 2018-04-19 14:26
http://forum.arduino.cc/index.php?topic=539489.0

http://forum.arduino.cc/index.php?topic=542465.0

**Comment by zmoog** [comment] 2021-01-29 16:40
@umbynos I checked on a Windows 10 machine and and I confirm the Agent 1.2 installer requires admin privileges (the app icon has the blue and yellow shield and the User Account Control (UAC) kicks in when you run it).

**Comment by per1234** [comment] 2023-11-18 18:28
Closing as duplicate of https://github.com/arduino/arduino-create-agent/issues/673. Even though this one was submitted much earlier, the other contains more information so I give it preference.

**Closed by per1234** 2023-11-18 18:28 UTC
Labels: topic: code, os: windows, type: imperfection
